spring:
  application:
    name: itracker
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        
cors:
  allowed-origins: http://localhost:3000
