spring:
  application:
    name: itracker
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true

logging:
  level:
    org.hibernate.SQL: debug

cors:
  allowed-origins: http://localhost:3000

selenium:
  driver-url: http://localhost:4444
